# Generated by Django 5.2.3 on 2025-06-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfollows",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
