# Generated by Django 5.2.3 on 2025-06-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_userfollows_is_blocked"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-time_created"]},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["-time_updated"]},
        ),
        migrations.AddField(
            model_name="review",
            name="time_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="time_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
